### ISSUE TITLE
Improve locale handling when title config not present

### ISSUE THREAD

**Issue by 3xkrazy** [chaoskagami/corbenik#15]
It would be nice if corbenik that defaults to a set global locale for titles when /corbenik/locale/TITLE is not present. As you already know, the issue is with loading out of region tiles that have multiple languages available, but defaults to the console's region (annoying for people who imported). For example, loading a USA Bravely Second cia will default to JPN language on a JPN console.

**Comment by chaoskagami** [comment]
The default global locale is whatever your console has it set as. If you have a US console set to english, then it's USA EN. Japanese console set to japanese? JPN JA.

I may be able to derive the correct region from a game's header by using the region lockout value (provided it hasn't been tampered with like region free CIAs) but a 'global' configuration is too prone to false positives and isn't a benefit.

A lot of Japanese games don't ship english files on them and it can cause strange bugs with the wrong region.

I can understand why you would suggest this, but if you're using a japanese console as a USA one, why not just regionswap it?

I may someday implement an on-console helper app to change settings that can be changed after the console has booted. That I feel is a better idea.

https://github.com/AuroraWright/Luma3DS/pull/48 provides more background.

**Comment by shinji257** [comment]
Region swapping isn't a sane option for most people.  Yes it can be done but usually at the cost of eShop access for those that want it.  As far as I know only the O3DS was able to overcome that cleanly assuming the circumstances were right.  N3DS units could only gain eShop access post region swap via a hack using NTR and a rather complicated transfer process.

Anyways in the end I agree that a global locale/region setting isn't proper either.  Leave it at the default and override per game.

**Comment by chaoskagami** [comment]
Closing this as stale. It takes too much effort to improve for too little gain.
