### ISSUE TITLE
 Place *.cetk and *.key files in its own directory 

### ISSUE THREAD

**Issue by 3xkrazy** [chaoskagami/corbenik#16]
corbenik already does this with:
/corbenik/firmware/
--agb
--native
--twl

so keeping with its standard, why not with:
/corbenik/cetk/
--agb.cetk
--native.cetk
--twl.cetk

and:
/corbenik/keys/
--11.key
--agb.key
--native.key
--twl.cetk

**Comment by chaoskagami** [comment]
There's this point where there's too many folders. I can do that, but it isn't really all that high on my priorities.

The only thing the cetk is used for is to derive the key, so I felt it appropriate to put it in keys. I'll think about it.

**Comment by chaoskagami** [comment]
Unless someone else pops up and thinks this is a good idea, I feel we're beginning to get too many folders and this actually harms organization somewhat (personal opinion, I guess.)

I'm closing it for now, but if anyone else shows interest, I'm perfectly fine with re-opening.
