### ISSUE TITLE
VM Enhancements

### ISSUE THREAD

**Issue by chaoskagami** [chaoskagami/corbenik#21]
The VM might be something we want a few enhancements on, like:
- [ ] rel offset to top and bottom framebuffer (rate limit writes to 30FPS)
- [ ] Button checks.
- [ ] Delaying.

**Comment by chaoskagami** [comment]
After consideration, I've decided (again) against these changes. I don't feel these have any place in the VM. Closing.

**Comment by fox8091** [comment]
I honestly believe at least delays should be added..

**Comment by chaoskagami** [comment]
I'm sorry, I have to disagree. Allowing patches to delay is stupid, imo. It has legitimate use in combination with buttons, but otherwise it serves only to slow startup.

Plus, loader and boot share the same interpreter. Given that there's no way to do anything aside from patch in loader, this is off the table.

Sorry.

**Comment by fox8091** [comment]
I was thinking for loader patches. May not be useful right now, but it could be useful to patch a sysmodule, wait on it to use your patched value, and then patch again. Basically, ROP via patching. :) But useless for everything but reimplementing *hax on boot or implementing ctr-httpwn without using *hax. :P

**Comment by chaoskagami** [comment]
The program isn't run until after loader executes it - which is long after it patches the code. That isn't how loader works.

**Comment by chaoskagami** [comment]
Not to mention that ctr-httpwn is largely uneeded on CFW - you can just kill the update checks in the code (which is what the friends module patch and the kill updates patch series are for.)

**Comment by fox8091** [comment]
Oh yea, we can only patch on startup.. And that's not all ctr-httpwn is useful for. :)

**Comment by chaoskagami** [comment]
That I won't argue. Replacing the certificate can have other uses aside from blocking updates, but that's a patch that has to be done either post-execute or in the romfs, and delays won't help here.

**Comment by fox8091** [comment]
Yea. While I don't agree with the decision to exclude it due to "why would I need this", it is your CFW, so if you don't see a use, that's your choice. :) Btw, I've grown quite fond of this CFW.

**Comment by chaoskagami** [comment]
At this point in time, delays have no use objectively speaking.

If I ever get resident code in memory that can patch at runtime, it would be useful for the reason you stated - patch, wait, patch. It could be used for timing sensitive operations when modifying memory.

Right now, Corbenik doesn't have the ability to do that, and therefore it isn't something needed until I get that working (if ever.)

Thanks, btw. :P

**Comment by fox8091** [comment]
No problem. :D
