### ISSUE TITLE
Green topbar should be wider

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#22]
![pic](http://image.prntscr.com/image/2895e5cae930470a8369c9d3fdcc133c.jpeg)

As you see, I think it should be slightly wider as to cover the whole top.

It's not noticeable on a black screen, but if you use a background, it certainly is.

**Comment by chaoskagami** [comment]
I'm aware of why you suggest this - hell, I agree.

It's harder than it sounds though, and entirely cosmetic.

The green bar is inverted spaces to the maximum character width. It just so happens that with the current font - the maximum number of characters doesn't quite reach the edge of the top screen, unfortunately.

I'd have to implement a draw_bar like function to do it.

**Comment by gnmmarechal** [comment]
All right, this is a workaround:
![Image](https://i.gyazo.com/7b606fdf61d017f644aab913a2827b46.png)

PDN file (for Paint.NET) can be found at http://github.com/gnmmarechal/corbenik-wallpaperlayer

**Comment by gnmmarechal** [comment]
Unfortunately, it IS noticeable when you don't go into the Corbenik menu, it's an ugly green rectangle in a corner.

![screenshot](https://cloud.githubusercontent.com/assets/11259227/16417533/32d5d05a-3d3e-11e6-9431-e57c61d9af21.png)

**Comment by chaoskagami** [comment]
Let me also remind you that this, amongst other reasons is why wallpapers aren't in a stable yet. Patience.

In the greater scheme of things - this is 9x4 pixels and is more lines of code than you think to fix. It's also entirely aesthetic.

If you do this in any transparent linux terminal by printing ANSI color codes with spaces, you'll get the same result with a non-character spaced size.

**Comment by chaoskagami** [comment]
Closing as fixed with 3f8fa694d8f49c5f68e3d49a43fdc78727250d89.
