### ISSUE TITLE
Parallel make is broken

### ISSUE THREAD

**Issue by chaoskagami** [chaoskagami/corbenik#27]
When I merged ctr9io, I forgot that the build method bombs out due to makefiles not allowing dependencies as such.

The only real solution is to build externally or finish switching to autoconf, so make won'y work parallel atm.

This is a notice to people compiling corbenik so they aren't surprised. Yes, it's broken.

**Comment by gnmmarechal** [comment]
rip Corbenik-UN. Will Skeith nightlies still work?

**Comment by chaoskagami** [comment]
Just compile with one core. My builds are done -j1 so they don't choke my computer, so skeith builds will continue to be produced.

Realistically, I can also fix the dependencies in tha makefile - but that may be a bit hard.

**Comment by gnmmarechal** [comment]
I set my VM to only have one core, still fails for some reason.

**Comment by chaoskagami** [comment]
If you're using -jN that's what breaks it. You can have multiple cores, just not multiple jobs. Either don't specify the -jN option or use -j1. I'm rewriting the makefile now so this hopefully will be closable soon.

**Comment by gnmmarechal** [comment]
Where can I find said option? I can't find any mention of -jN anywhere in the makefile.

**Comment by chaoskagami** [comment]
...It's an option you provide to the 'make' command. If you're calling straight 'make' with no options, you'll succeed as per usual.

Either way, autotools porting is _mostly_ done, but it's been a royal PITA.

**Comment by gnmmarechal** [comment]
Actually, I've been calling "make", and it fails.

![](http://image.prntscr.com/image/e60fc1f3c87c4b0c90886647390d6124.png)

**Comment by chaoskagami** [comment]
This has nothing to do with this bug. You didn't checkout libctr9 properly.

Please just re-clone the entire sourcebase with `git clone --recursive https://github.com/chaoskagami/corbenik`

**Comment by gnmmarechal** [comment]
oh. I was sure I'd done it. Oh well.

**Comment by chaoskagami** [comment]
Still broken after merging amport, but much easier to fix now. I'm just kind of lazy.
