### ISSUE TITLE
(Nightly only) EmuNAND broke

### ISSUE THREAD

**Issue by chaoskagami** [chaoskagami/corbenik#30]
At some point in the nightly builds, EmuNAND broke. I need to fix it (ugh)

**Comment by gnmmarechal** [comment]
Huh. I'm going to start using EmuNAND just for the lulz, it's the one thing I never tried with Corbenik.

**Comment by GrayJack** [comment]
Any EmuNAND or just GW emuNAND?
My RedNAND is working with the last nightly, but takes a lot of time to boot

**Comment by chaoskagami** [comment]
When I say EmuNAND I mean all emuNAND but I'm incapable of repro'ing this one. According to him, the last stable works and the nightlies don't. He has a RedNAND.

I'll leave this up for a bit, but it may have been a false alarm.

**Comment by gnmmarechal** [comment]
So is this going to stay open? Did you ever find something out about this?

**Comment by chaoskagami** [comment]
No, I didn't. I think it's probably about time to close it as "can't repro". Need a label for that...
