### ISSUE TITLE
300 permanent coins

### ISSUE THREAD

**Issue by droped** [chaoskagami/corbenik#34]
Or just set them to 300 at boot.

**Comment by chaoskagami** [comment]
Code a patch yourself and PR to contrib if you really want this. Or use one of the N play coin setters in existence.

Closing.

**Comment by ghost** [comment]
How dare you suggest coin piracy poutros.

**Comment by dankzegriefer** [comment]
idgrepthat, he was refering to play coins.

**Comment by gnmmarechal** [comment]
This is pretty useless tbh, is it that hard to open one of the quick 300 coin setters?
