### ISSUE TITLE
Build error in firm/firm.c

### ISSUE THREAD

**Issue by mariogamer2** [chaoskagami/corbenik#35]
Here is the error:

firm/firm.c: In function 'dump_firm':
firm/firm.c:57:22: warning: cast increases required alignment of target type [-Wcast-align]
     sdmmc_get_cid(1, (uint32_t_)cid);
                      ^
firm/firm.c: In function 'decrypt_cetk_key':
firm/firm.c:211:5: error: implicit declaration of function 'cbc_decrypt' [-Werror=implicit-function-declaration]
     cbc_decrypt(key, key, 1, AES_CNT_TITLEKEY_DECRYPT_MODE, iv);
     ^
firm/firm.c: In function 'decrypt_firm_title':
firm/firm.c:230:53: error: 'AES_CNT_CBC_DECRYPT_MODE' undeclared (first use in this function)
     cbc_decrypt(ncch, ncch, *size / AES_BLOCK_SIZE, AES_CNT_CBC_DECRYPT_MODE, f
                                                     ^
firm/firm.c:230:53: note: each undeclared identifier is reported only once for each function it appears in
firm/firm.c:240:22: warning: cast increases required alignment of target type [-Wcast-align]
     exefs_h *exefs = (exefs_h *)((uint8_t *)ncch + ncch->exeFSOffset \* MEDIA_UN
                      ^
firm/firm.c: In function 'decrypt_arm9bin':
firm/firm.c:275:9: error: implicit declaration of function 'ecb_decrypt' [-Werror=implicit-function-declaration]
         ecb_decrypt(header->slot0x16keyX, decrypted_keyx, 1, AES_CNT_ECB_DECRYP
         ^
firm/firm.c:275:62: error: 'AES_CNT_ECB_DECRYPT_MODE' undeclared (first use in this function)
         ecb_decrypt(header->slot0x16keyX, decrypted_keyx, 1, AES_CNT_ECB_DECRYP
                                                              ^
firm/firm.c: In function 'boot_firm':
firm/firm.c:432:43: error: 'AES_CNT_ECB_DECRYPT_MODE' undeclared (first use in this function)
             ecb_decrypt(keydata, keyx, 1, AES_CNT_ECB_DECRYPT_MODE);
                                           ^
firm/firm.c: In function 'find_proc9':
firm/firm.c:482:13: warning: assuming pointer wraparound does not occur when comparing P +- C1 with P +- C2 [-Wstrict-overflow]
             while (arm9section < arm9section + section->size) {
             ^
firm/firm.c:484:36: warning: cast increases required alignment of target type [-Wcast-align]
                     ncch_h *ncch = (ncch_h *)((uint8_t_)arm9section - sizeof(nc
                                    ^
cc1: all warnings being treated as errors

**Comment by chaoskagami** [comment]
I can't repro this, but it looks like you're building against an old libctr9. Update your submodules, or reclone entirely?

On August 29, 2016 3:14:20 PM EDT, mariogamer2 notifications@github.com wrote:

> Here is the error:
> 
> `firm/firm.c: In function 'dump_firm':
> firm/firm.c:57:22: warning: cast increases required alignment of target
> type [-Wcast-align]
>     sdmmc_get_cid(1, (uint32_t*)cid);
>                      ^
> firm/firm.c: In function 'decrypt_cetk_key':
> firm/firm.c:211:5: error: implicit declaration of function
> 'cbc_decrypt' [-Werror=implicit-function-declaration]
>     cbc_decrypt(key, key, 1, AES_CNT_TITLEKEY_DECRYPT_MODE, iv);
>     ^
> firm/firm.c: In function 'decrypt_firm_title':
> firm/firm.c:230:53: error: 'AES_CNT_CBC_DECRYPT_MODE' undeclared (first
> use in this function)
> cbc_decrypt(ncch, ncch, *size / AES_BLOCK_SIZE,
> AES_CNT_CBC_DECRYPT_MODE, f
>                                                     ^
> firm/firm.c:230:53: note: each undeclared identifier is reported only
> once for each function it appears in
> firm/firm.c:240:22: warning: cast increases required alignment of
> target type [-Wcast-align]
> exefs_h *exefs = (exefs_h *)((uint8_t *)ncch + ncch->exeFSOffset *
> MEDIA_UN
>                      ^
> firm/firm.c: In function 'decrypt_arm9bin':
> firm/firm.c:275:9: error: implicit declaration of function
> 'ecb_decrypt' [-Werror=implicit-function-declaration]
> ecb_decrypt(header->slot0x16keyX, decrypted_keyx, 1, AES_CNT_ECB_DECRYP
>         ^
> firm/firm.c:275:62: error: 'AES_CNT_ECB_DECRYPT_MODE' undeclared (first
> use in this function)
> ecb_decrypt(header->slot0x16keyX, decrypted_keyx, 1, AES_CNT_ECB_DECRYP
>                                                              ^
> firm/firm.c: In function 'boot_firm':
> firm/firm.c:432:43: error: 'AES_CNT_ECB_DECRYPT_MODE' undeclared (first
> use in this function)
>             ecb_decrypt(keydata, keyx, 1, AES_CNT_ECB_DECRYPT_MODE);
>                                           ^
> firm/firm.c: In function 'find_proc9':
> firm/firm.c:482:13: warning: assuming pointer wraparound does not occur
> when comparing P +- C1 with P +- C2 [-Wstrict-overflow]
>             while (arm9section < arm9section + section->size) {
>             ^
> firm/firm.c:484:36: warning: cast increases required alignment of
> target type [-Wcast-align]
>            ncch_h *ncch = (ncch_h *)((uint8_t*)arm9section - sizeof(nc
>                                    ^
> cc1: all warnings being treated as errors
> `
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/chaoskagami/corbenik/issues/35

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aorin-sound** [comment]
clone using the flag --recurse-submodules

**Comment by chaoskagami** [comment]
I seriously need more compile-time sanity checks... Is this the current bomb-out on no submodules, @udemiko?

Anyways, I'll be closing this since it's in all likelyhood not cloned properly.

**Comment by aorin-sound** [comment]
yeah, since git takes care of submodules if they are in source control, but they are not cloned automatically (and this is pretty much the only possible outcome). @mariogamer2, please note that if you downloaded the zipped version from github, that doesn't include submodules.

**Comment by mariogamer2** [comment]
I think that git does not properly update the submodule when we update the base repo (with a commit that update the submodule),anyway this work fine...

**Comment by fox8091** [comment]
mariogamer2: No..it doesn't ATTEMPT to update them. Do "git submodule update" to update submodules.

**Comment by chaoskagami** [comment]
@fox8091 is correct.
