### ISSUE TITLE
Corbenik doesn't compile

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#45]
Compiling gives me an error at block_cart_update.pco. Can't exactly paste the log right now, though. :/
https://github.com/chaoskagami/corbenik/commit/28e9cfac5e2fe052336925aa46ba02c5a4d93feb

I don't know if this is getting fixed and you expected this to break and are fixing it on your repo, but, well, I might as well report this issue. :D

**Comment by chaoskagami** [comment]
Pull, please~

https://github.com/chaoskagami/corbenik/commit/29135d1c265097cc447497b20612fcedbc3e75c6
