### ISSUE TITLE
Display patch name upon abort

### ISSUE THREAD

**Issue by kitlith** [chaoskagami/corbenik#46]
It would be nice if, when a patch aborts, it displayed the name of the patch that aborted, so that you can go in and disable the patch after rebooting. Useful when turning on a bunch of patches, and then one aborts... and you're not sure which one.

**Comment by chaoskagami** [comment]
Unfortunately, the current method of application (building a patch cache) prevents this from being possible. All the patches end up combined together into titleid-named blobs of bytecode.

It might take a bit to fix this, but I tend to agree it would be useful now that corbenik doesn't just completely die upon failure.

**Comment by chaoskagami** [comment]
An opcode to print a null-terminated string was added to the VM and the caching was modified to insert OP_NEXT, OP_PRINT, "patch name", OP_NEXT before the bytecode is appended to the cache (the result being patch name printing before executing bytecode.)

When I get back, get at my ssh keys and push to the repo this will be closed.

**Comment by chaoskagami** [comment]
Closing. Cache now contains debugging information between concatenated patches. Checking logs can now give the patch it fails on (though it's still not as informative as exact line numbers; but I digress)
