### ISSUE TITLE
RomFS redirection and ips patcher (like Luma)

### ISSUE THREAD

**Issue by GrayJack** [chaoskagami/corbenik#47]
It's not something of high priority, but it would be a great enhancement. I don't care too much about this, but I do use it in 2 or 3 games.

It would be neat too if you could implement a RomFS dump like the code sections dump, only if it's possible, but that is more low priority (at least for me)

**Comment by chaoskagami** [comment]
RomFS redirection / dump: No. RomFS is a gigantic suboptimal waste of space compared to overlays. Dumping is not my job and it's better suited to some application that gives a visual progress indicator. Or ctrtool.

IPS patcher: No. Corbenik is already a very fancy patcher that does far more than an IPS, and this will only overcomplicate Corbenik into some mess which applies multiple types of patches.

As a side note, IPS as a format is limited to a maximum of 32MB (so long as one is not using an extension such as IPS32.) It'd be trivial to write something like an IPS -> VCO compiler.

LayeredFS: Waiting. @delebile seems to be doing work on this in his Luma fork. I'll integrate this whenever it gets stabilized and I have enough time to sift through and figure out how it works.

All-in-all, this is already covered by #6. Closing.

**Comment by GrayJack** [comment]
If it was already covered by #6 then it would be more logical to say "RomFS redirection yes, but for latter and RomFS dump no" or "it's covered by #6 but I'll not do it, at least for now" or something like it.

And I didn't know that Delebile was working in LayeredFS, that is awesome!!! I'm looking forward  for this feature to be implemented :3

**Comment by chaoskagami** [comment]
On the topic of IPS patching; I kind of wanted to play Waning Moon, and this shit happened: https://github.com/chaoskagami/corbenik/commit/f144539432836911430458159406ddbd4de48b8c

Not exactly an IPS patcher in corbenik per-se, but certainly usable to convert them. ;P
