### ISSUE TITLE
Autoboot+Silent Mode with no top/bottom splash should avoid initializing the display

### ISSUE THREAD

**Issue by chaoskagami** [chaoskagami/corbenik#48]
Ideally, Autoboot and Silent Mode together should not initialize the screen unless the menu key (R) is held.

**Comment by gnmmarechal** [comment]
What about getting a boot splash? Not initializing the screen would make it not show.

**Comment by chaoskagami** [comment]
Which is why I specifically stated "with no top/bottom splash" e.g., there must not be a splash present for this behavior.

Hell, I could add another toggle, but why would someone want to have it be vanilla-ish non-si boot and decorated? Makes very little sense to me.

**Comment by gnmmarechal** [comment]
Oh, didn't see that on the title. Rip.

**Comment by chaoskagami** [comment]
¯\_(ツ)_/¯

**Comment by chaoskagami** [comment]
This has been implemented in my local tree. Whenever I get back it'll be pushed.
