### ISSUE TITLE
Question about Skeith building

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#49]
So, I want to build Corbenik as Skeith as not to replace the stable, but I can't seem to figure out how to do so. Where do I change the directory for the CFW?

**Comment by chaoskagami** [comment]
https://github.com/chaoskagami/skeith/blob/master/checkbuild.sh#L48

Add `--prefix=/skeith` to the configure command. That sets the "prefix" on the 3DS to `/skeith` (or really, `sdmc:/skeith`.) The default prefix is `/corbenik` as you'd probably expect.
