### ISSUE TITLE
Add the ability for cross-region dl play

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#50]
https://github.com/AuroraWright/Luma3DS/pull/305/files

Something like that. it doesn't have it yet, does it?

**Comment by chaoskagami** [comment]
I'm currently at a family house out of state (and don't have ssh keys on this computer) so I'm incapable of committing this at the moment, or testing, but this should work (as a quick adaptation):

```
# $name  DLP Region Fix (Loader)
# $desc  Disables region check in DLP
# $title 0004013000002802
# $ver   01
# $uuid  20

rel exe_text

find 0CACC0D8
abortnf
# nop (andeq r0, r0, r0) ?
set  00000000
```

**Comment by gnmmarechal** [comment]
I can add it and do a PR if you want. I can't test atm either, though.

**Comment by chaoskagami** [comment]
I'd prefer to add this myself when I get the chance. I've assigned myself.

Next chance I get will be in about two days, and I have a few other miscellaneous changes I intend to make then, as well.

**Comment by gnmmarechal** [comment]
All right, then.

**Comment by sykhro** [comment]
It's not really a nop; we patch the result code to always be 0 (0xD8C0ACC0 corresponds to "Not supported" in the dlp module) thus making the dlp init function go on

**Comment by chaoskagami** [comment]
I was unsure whether it was data or code; DWORD 0x0 in arm asm _is_ a nop, and I haven't looked at DLP's code myself. I didn't take enough time to realize that was a result code (it looked more like an opcode from a glance :s)

A result code being patched to successful would normally mean it's data...is this the usual value shoved into .text between functions like ninty's compilers tend to do, or is this value in .data / .ro? If so, it's possible that exe_text is also incorrect here.

**Comment by chaoskagami** [comment]
Seems it's within .text. Anyways, this has been implemented in my local tree and will be pushed when I get back.

**Comment by chaoskagami** [comment]
Pushed work, patch *should* function although it's not been given extensive testing. If it doesn't work, comment on this and I'll reopen if needed.
