### ISSUE TITLE
Skeith doesn't show boot splash

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#51]
So. The top splash shows up if I enter the menu, but NOT if I don't and just autoboot.

The bottom image never shows up.

**Comment by chaoskagami** [comment]
I know why the only-one-bg behavior happens just recalling off memory. I changed the background load code to something like this:

if (loadtop || loadbottom)

Unfortunately, I wasn't thinking straight. This thing called short circuit evaluation exists, and I somehow managed to forgot. Actually: if only a bottom is present, it will probably show the bottom one. Easy fix, anyways.

As for the lack of splash on boot: Is the backlight on? If so, currently, zero screen clears occur post-background-load wheras before, at least one always would. I'd assume that's it. Minor oversight.

Normally I'd say "I'll fix it tomorrow" but I'll fix it on the 5th or 6th. I'll be too busy opening gifts, playing games, and scarfing down cake for that. ;)

On January 3, 2017 6:34:53 PM EST, "Mário Alexandre Lopes Liberato" <notifications@github.com> wrote:
>So. The top splash shows up if I enter the menu, but NOT if I don't and
>just autoboot.
>
>The bottom image never shows up. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chaoskagami/corbenik/issues/51

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gnmmarechal** [comment]
Yep, the backlight is on, the text on the bottom screen also shows up. Just not the splash.

Thanks!

**Comment by chaoskagami** [comment]
This should be fixed now. Whenever Jenkins performs a build (within the hour) I suppose we'll know.

**Comment by gnmmarechal** [comment]
Yep, it's fine now.
