### ISSUE TITLE
Skeith and HighMem Games (O3DS)

### ISSUE THREAD

**Issue by ghost** [chaoskagami/corbenik#56]
I encountered an issue earlier today with Skeith CFW. For some reason, whenever I load a HighMem game on my 3DS, it will not reboot. I just wanted to bring this to your attention and help you out. Thank you so much for developing this CFW!

P.S. I also checked in-case I forgot to enable reboot patches, but they were enabled...

**Comment by MegaPramuk** [comment]
Have you tried [this](https://github.com/chaoskagami/corbenik/issues/39#issuecomment-259767396)?

**Comment by chaoskagami** [comment]
It's interesting, though. I've recieved that report before; I'm unable to reproduce it, no matter what I try.

**Comment by gnmmarechal** [comment]
Last time it happened to me, doing a clean setup of Skeith seemed to fix it.

**Comment by ghost** [comment]
Doing a clean Skeith setup seemed to do the trick. That was a really odd bug though...

**Comment by chaoskagami** [comment]
Since nobody seems to have any clue what causes this, I'm closing this to clean up the issue tracker of non-bugs.

**Comment by ghost** [comment]
I have a feeling this is due to native.dec not being properly cleaned - some people had this issue when upgrading to 11.3 and trying to use the new FIRM

**Comment by chaoskagami** [comment]
That doesn't really make sense though; the console wouldn't boot with an 11.2 nfirm. Somehow it would have to be p_native that's the problem, and that gets nuked immediately on entering the config menu. :/
