### ISSUE TITLE
Firmware info (like Cakes)

### ISSUE THREAD

**Issue by GrayJack** [chaoskagami/corbenik#60]
Another idea for enhancement. 
Maybe together with Build Info, put what NATIVE/AGB/TWL_FIRM version is being loaded from SD. It's not something I care too much, but I seen to keep forgetting what firmware I used last for testing (normally my emuNAND) days after making the test an trying to load sysNAND and maybe it's helpful for someone else too.

**Comment by chaoskagami** [comment]
Nope. Here's why:

 * We use a heuristic for FIRM detection (unlike cakes), and without poking through the kernel to extract the version we actually have no clue what version it is at runtime.
 * This would interfere with the future implementation of a FIRM switcher.

Corbenik used to have this before heuristic FIRM detection was implemented. It was removed for the above reasons.

On February 12, 2017 9:37:09 PM EST, GrayJack <notifications@github.com> wrote:
>Another idea for enhancement. 
>Maybe together with Build Info, put what NATIVE/AGB/TWL_FIRM version is
>being loaded from SD. It's not something I care too much, but I seen to
>keep forgetting what firmware I used last for testing (normally my
>emuNAND) days after making the test an trying to load sysNAND and maybe
>it's helpful for someone else too.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by GrayJack** [comment]
Yeah, I realized that when I read the code that get the firm info, after I posted in here.
Thanks anyway

**Comment by chaoskagami** [comment]
TBH, if I could find some easy way to extract the kernel version and display it, I would.

There's always 3DSIdent, assuming osGetKernelVersion gets the version from the running kernel and not the NAND cxi.
