### ISSUE TITLE
f flag not set, halting vm

### ISSUE THREAD

**Issue by scorp1onSlayer** [chaoskagami/corbenik#62]
idk what is happening i click boot firmware and i get this

**Comment by scorp1onSlayer** [comment]
heres the boot log
[boot.txt](https://github.com/chaoskagami/corbenik/files/852027/boot.txt)

**Comment by chaoskagami** [comment]
RTFM.

You likely have keys or firmware improperly set up.

**Comment by scorp1onSlayer** [comment]
but all of the firmwares and cteks are in the right place and all the keys have generated so idk what you mean

**Comment by chaoskagami** [comment]
Simply put, this error will never occur unless you set up something wrong, or you're using an unsupported or corrupted FIRM.

Something I didn't catch before; are you using the stable release off github? Some of the patches are named incorrectly (or rather, have names not reflecting the current state in git.)

**Comment by scorp1onSlayer** [comment]
yes i am using the stable realese on the git hub

**Comment by scorp1onSlayer** [comment]
![capture](https://cloud.githubusercontent.com/assets/25756922/24378542/89fd7a16-1300-11e7-91e9-62d3ac6c5149.PNG)
this is the firmware folder screenshot just incase

**Comment by ghost** [comment]
In any case, the important bits would be file sizes and hashes of some sort - even md5 would be enough to verify.

**Comment by scorp1onSlayer** [comment]
![capture](https://cloud.githubusercontent.com/assets/25756922/24379352/f6cbac6e-1303-11e7-8253-e98f16bf1d04.PNG)
well then heres one with the file sizes

**Comment by ghost** [comment]
ugh... remove all decrypted files, post SHA256 hashes of all keys, and provide *some* information.
At this point, I can't even tell if you're on old or new 3DS. You even enabled the TWL patches for both consoles.

Also, try with the latest release from a few minutes ago.

**Comment by chaoskagami** [comment]
Uh, they both are enabled by design. They share the same UUID, and since patches are applied to FIRM by titleid, you only get the proper one applied for whatever firm is there.

But yes, the old stable is broken as fuck and some patch names in the log indicate an old release with bugs present (e.g. I spot an 11.0 in the log, not 11.0+ as it is now in the name)

**Comment by scorp1onSlayer** [comment]
this issue is finally over as i did nothing wrong it was the old stable version causing it

**Comment by scorp1onSlayer** [comment]
the new one totally fixed it
