### ISSUE TITLE
Doesn't build on macOS Sierra.

### ISSUE THREAD

**Issue by KittyCatCode** [chaoskagami/corbenik#63]
After running make, gcc says 
`clang: error: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated`

**Comment by sykhro** [comment]
You can't use OSX's pseudo-gcc clang to compile this. You need the arm cross-compiler that comes with devkitpro.

**Comment by KittyCatCode** [comment]
I know. It's strange because I configured it correctly, and it said that it was using arm-none-eabi-gcc. IDK why it would be using the built-in compiler.

**Comment by KittyCatCode** [comment]
Corbenik 0.3.0
    ========================
    Prefix:          /corbenik
    
    cc:              arm-none-eabi-gcc
    cxx:             arm-none-eabi-g++
    ld:              /Volumes/MACFILES/Users/gabriel/devkitPro/devkitARM/arm-none-eabi/bin/ld
    oc:              arm-none-eabi-objcopy
    
    sed:             /usr/bin/sed
    
    cflags:          -g -O2
    cxxflags:        -g -O2
    ldflags:         
    ocflags:         
    
    Chainloader:     1
    
    Configure:       --host=arm-none-eabi
    Compiler ID:     arm-none-eabi-gcc (devkitARM release 45) 5.3.0

edit: formatting

**Comment by sykhro** [comment]
mh.. try passing -std=c99 in the cflags

**Comment by KittyCatCode** [comment]
Where do i add that to the cflags? I tried adding "CFLAGS+=" -std=c99"" to configure.ac, then autoconf, then ./configure and it looked like it worked:

`cflags:          -g -O2 -std=c99`

But when I run make -j4 it completely ignores it:

    gcc -o error_decoder error_decoder.c -g -O0
    g++ -c -Wall -Werror -g -DOSSD_TARGET=OSSD_IF_LINUX main.c -o main.o
    g++ -c -Wall -Werror -g -DOSSD_TARGET=OSSD_IF_LINUX bdf.c -o bdf.o

**Comment by chaoskagami** [comment]
That's one of the host tools that gets built with the host compiler (XCode in your case, meaning clang.)

It's odd that g++ is being used there (not gcc.) It's not c++ code; it shouldn't be using a c++ compiler.  clang probably is more strict.

I'll take a look at this tomorrow. I suspect something is incorrect in a makefile somewhere and gcc is being looser than clang in behavior.

On March 25, 2017 1:10:37 PM EDT, KittyCatCode <notifications@github.com> wrote:
>Where do i add that to the cflags? I tried adding "CFLAGS+=" -std=c99""
>configure.ac, then autoconf, then ./configure and it looked like it
>worked:
>
>`cflags:          -g -O2 -std=c99`
>
>But when I run make -j4 it completely ignores it:
>
>    gcc -o error_decoder error_decoder.c -g -O0
>   g++ -c -Wall -Werror -g -DOSSD_TARGET=OSSD_IF_LINUX main.c -o main.o
>    g++ -c -Wall -Werror -g -DOSSD_TARGET=OSSD_IF_LINUX bdf.c -o bdf.o
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/chaoskagami/corbenik/issues/63#issuecomment-289225411

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chaoskagami** [comment]
Try now on the latest commit (more specifically, the bdfe submodule.) As I suspected, bdfe (which is C code) had g++ being used as the compiler for some inexplicable reason. It should succeed now.

**Comment by chaoskagami** [comment]
I've received no confirmation of whether this is fixed or not, so I'm closing on assumption I've resolved the issue.
