### ISSUE TITLE
corbenik unable to boot region changed 3DS

### ISSUE THREAD

**Issue by MegaPramuk** [chaoskagami/corbenik#69]
Exactly what it says.
Due to several reasons I decided to change my o3DS' region to Japan and corbenik has been unable to boot it since (on both 9.2.0-20J and 11.4.0-37J).
Luma3DS booted just fine into both 9.2.0-20J and updated to 11.4.0-37J.
Weird thing however is that I had region changed my o3DS at some point to Japan and back then it worked (either 11.1.0-34 or 11.2.0-35 were the latest update).
[Here](https://my.mixtape.moe/lhbyzt.zip) are the logs of corbenik's successful and failed boot for 11.4.0-37{E,J} respectively. Running `diff` on the logs shows that the region changed one just stops midway and it doesn't matter how long I wait on this one.
corbenik was also built on the latest commit (1032b8c).

**Comment by chaoskagami** [comment]
The boot.log is incomplete and starts in the middle of the patching process for both provided logs. Can you provide a full log, please?

Unfortunately, in this specific case, the loader.log is useless. It seems to be hung, but I can't think of any possible codepaths where a hang is even possible there.

**Comment by MegaPramuk** [comment]
That's what the o3DS gave me several times, more or less the same at least.
But deleting the config and enabling the patches again fixed this.
Anyway, I hope that this time it helps you more.
https://my.mixtape.moe/jsjeti.log

**Comment by chaoskagami** [comment]
The new log you posted does not have 'SecureInfo_A Signature Fix (Loader)' enabled. This is mandatory on region changed consoles. If you had this disabled, it's no wonder your console wouldn't boot.

Since you appear to have resolved the issue, I'll go ahead and close this.
