### ISSUE TITLE
Wiki Mistake

### ISSUE THREAD

**Issue by Noodlez1232** [chaoskagami/corbenik#73]
In bytecode for the op fwd it says "number of bytes to rewind" which I'm pretty sure is incorrect.

**Comment by chaoskagami** [comment]
Yes, it is. The wiki documentation is severely out of date; I'm not even sure the opcode map is correct at this point. I've neglected to update it.

**Comment by chaoskagami** [comment]
I've fixed this mistake, but as per usual; the notice at the top applies.
