### ISSUE TITLE
3DS Banwave 

### ISSUE THREAD

**Issue by Derek1199** [chaoskagami/corbenik#74]
I understand there is probably no way to fix this at all except for disabiling sending of information and hiding what title is currently being played in the friends list applet. But we need a way to patch it so nintendo can't ban people like that. The cause of the ban is the friends list applet. Basically what is happening is a invalid title ID is seen, then a ban request is sent, then the user's 3ds gets banned from online play. The only way to unban is to inject a not banned localfriendseed_B  or sell themselves to hackerone. This is a very serious issue. Affecting all cfw users.

**Comment by chaoskagami** [comment]
Except I'm not banned, and furthermore, my Mii has gold pants, and my Pokemon save has been slightly tampered with.

Closing as invalid. I don't know what the ban criteria is, and I can't fix something without a known cause. Arguably, you know what you've gotten into by installing CFW in the first place.

**Comment by dogtopus** [comment]
I see how this may become an issue in the future. That's why I have a all-zero LFCS and a randomized SecureInfo (No you cannot play online with all-zero LFCS but I won't play online on my <strike>piracy</strike>homebrew console anyway)

**Comment by Derek1199** [comment]
That's not the point. Many are getting banned. Basically this is Nintendo's
reaction to b9s being released. Because b9s gives us access to the bootrom.
Plus it can be installed even on 11.4 with a hardmod and dsiwarehax. Thus
banwave is similar to the pokemon sun/moon one though as they both have the
same error code. But the pokemon sun/moon banwave banned localfriendseed_B
and nnidsave and secureinfo_A as well. While this cfw banwave only bans the
localfriendseed_B. And hexediting the localfriendseed_B won't unban us
because it's not signed by the bootrom signature. It's signed by Nintendo.
So we would have to inject a not banned one. Anyway Nintendo started this
banwave on Monday, a week ago. Nintendo is basically pissed. Users that go
in system settings, Internet settings then spotpass and turn off sending of
information and then go to friend list to hide what title their playing are
safe from being banned.

**Comment by fox8091** [comment]
Who cares what the point is? You break the ToS, you risk a ban. Point blank. It's not chaoskagami's job to fix your or anyone else's mistake. This isn't even client side, it's server side. Accept it, bans happen. CFW can't really fix it.

**Comment by Derek1199** [comment]
Yeah, true. It would be nice to have it fixed though. If this could be fixed though, we would need to find a way to prevent this information from being sent without changing the aforementioned settings that I just mentioned. BOSS would probably need patched for this. So, yeah.

**Comment by fox8091** [comment]
That's not something the CFW _should_ do even. Either disable the settings or deal with the risk. 👎

**Comment by chaoskagami** [comment]
Here's an idea: don't use online functionality or leave "supply data to nintendo" options enabled if you don't want information to be gathered, sat on, and subsequently used to ban your console. Read: @fox8091 is right on the money. It's not rocket science, @Derek1199.

If you want to implement privacy patches or whatever, have fun. You're on your own; it's outside the scope of what I'm willing to do. I'm under no obligation to implement/reverse engineer anything.

It seems I'm being not-so-subtly ordered to implement something that's out of scope, so for the first time in this project's history I'm locking discussion. Show's over.
