### ISSUE TITLE
Doesn't actually boot.

### ISSUE THREAD

**Issue by wowitsjack** [chaoskagami/corbenik#9]
Followed all instructions, tried multiple versions of all required files. Invariably boots with 'FAILED TO LOAD NATIVE_FIRM'. Needs complete overhaul.

**Comment by chaoskagami** [comment]
Enable 'Logging' and 'Verbose' in options, and upload the logs, or alternatively type the letters in the brackets up here - or I can't help you.

Also, you have no right to tell me to do a 'complete overhaul'.

That's a great way to start a bug report - piss off the dev. I'll give you the benefit of the doubt for now.

**Comment by chaoskagami** [comment]
Closing as invalid due to lack of proper debugging information and absurd requests.
